spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: -1

  datasource:
    url: jdbc:mysql://localhost:3306/info_1024
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  type-aliases-package: com.example.demo_mybatis.entity
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8080





    
